#!/usr/bin/with-contenv bash
CONFIG="/etc/dnsmasq.conf"
source /usr/lib/bashio/bashio.sh

# Run dnsmasq
bashio::log.info "Starting dnsmasq..."

# Set max open file limit to speed up startup
ulimit -n 1024

exec dnsmasq -C "${CONFIG}" -z < /dev/null

