---
version: 1.0.21
slug: dnsmasq
name: Dnsmasq
description: A simple DNS and DHCP server
url: https://github.com/k0s1nski/customha/tree/main/dnsmasqdhcp
advanced: true
apparmor: true
host_network: true
privileged:
  - NET_ADMIN
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image:  ghcr.io/k0s1nski/{arch}-addon-dnsmasqdhcp
init: false
options:
  defaults:
    - 1.1.1.1
    - 1.0.0.1
  forwards: []
  hosts: []
  services: []
  cnames: []
  log_queries: false
  log_dhcp: false
  dhcp: false
  dhcp_range: 192.168.0.100,192.168.0.200
  dhcp_netmask: 255.255.255.0
  dhcp_router: 192.168.0.1
  dhcp_dns: 1.1.1.1
  dhcp_ntp: 192.168.0.1
  dhcp_domain: example.lan
  cache_size: 150
ports:
  53/tcp: 53
  53/udp: 53
  69/udp: 69
schema:
  defaults:
    - str
  forwards:
    - domain: str
      server: str
  hosts:
    - host: str
      ip: str
  services:
    - host: str
      port: str
      priority: int
      srv: str
      weight: int
  cnames:
    - name: str
      target: str
  log_queries: bool
  log_dhcp: bool
  dhcp: bool
  dhcp_range: str
  dhcp_netmask: str
  dhcp_router: str
  dhcp_dns: str
  dhcp_ntp: str
  dhcp_domain: str
  cache_size: int
startup: system
